# Basic configs
baseURL = 'https://blog.tahacodes.io/'
languageCode = 'en'
defaultContentLanguage = "en"
theme = 'awesome'
title = "Taha's blog"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

# External links
[[params.socialIcons]]
name = "github"
url = "https://github.com/tahacodes"

[[params.socialIcons]]
name = "x"
url = "https://twitter.com/tahacodes"

[[params.socialIcons]]
name = "RSS"
url = "/index.xml"

[Languages.en]
languageName = "English"
languageCode = "English"
contentDir = "content/"
weight = 1

[Languages.en.menu]
[[Languages.en.menu.main]]
pageRef = "posts"
name = 'Posts'
url = '/posts/'
weight = 10

[Languages.en.params]
sitename = "Taha's blog"
defaultColor = "dark"
description = ""
mainSections = ['posts']
toc = true
tocOpen = false
goToTop = true
additionalScripts = []
dateFormat = ""
rssFeedDescription = "summary"

[Languages.en.params.author]
avatar = ""
name = "Taha Farahani"
intro = "Taha's blog"
description = "Things that i like talking about"
