# Basic configs
baseURL = 'https://blog.tahacodes.io/'
languageCode = 'en-us'
defaultContentLanguage = "en-us"
theme = 'awesome'
title = 'A Simple Blog'

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

# External links

[[params.socialIcons]]
name = "github"
url = "https://github.com/tahacodes"

[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/tahacodes"

[[params.socialIcons]]
name = "RSS"
url = "index.xml"

# set markup.highlight.noClasses=false to enable code highlight
[markup]
[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2  # ToC starts from H2
endLevel = 4    # ToC ends at H4
ordered = false # generates <ul> instead of <ol>

#### English language
[Languages.en-us]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 1

[Languages.en-us.menu]
[[Languages.en-us.menu.main]]
pageRef = "posts"
name = 'Posts'
url = '/posts/'
weight = 20

[Languages.en-us.params]
sitename = "Things that i enjoy talking about"
defaultColor = "dark"
description = ""
mainSections = ['posts']
toc = true
tocOpen = false
goToTop = true
additionalScripts = []
dateFormat = ""
rssFeedDescription = "summary"

[Languages.en-us.params.author]
avatar = ""
name = "Taha Farahani"
intro = "A Simple Blog"
description = "Things that i like talking about"

# Allow to override webmanifest options
[Languages.en-us.params.webmanifest]
name = "sitename"
short_name = "sitename"
start_url = "/"
theme_color = "#434648"
background_color = "#fff"
display = "standalone"

#### Persian language
[Languages.fa-ir]
languageName = "Persian"
languageCode = "fa-ir"
contentDir = "content/fa"
weight = 1

[Languages.fa-ir.menu]
[[Languages.fa-ir.menu.main]]
pageRef = "posts"
name = 'پست‌ها'
url = '/posts/'
weight = 20

[Languages.fa-ir.params]
sitename = "چیزهایی که دوست دارم درباره‌شان صحبت کنم"
defaultColor = "dark"
description = ""
mainSections = ['posts']
toc = true
tocOpen = false
goToTop = true
additionalScripts = []
dateFormat = ""
rssFeedDescription = "summary"

[Languages.fa-ir.params.author]
avatar = ""
name = "Taha Farahani"
intro = "یه بلاگ ساده"
description = "چیزهایی که دوست دارم درباره‌شان صحبت کنم"

# Allow to override webmanifest options
[Languages.fa-ir.params.webmanifest]
name = "sitename"
short_name = "sitename"
start_url = "/"
theme_color = "#434648"
background_color = "#fff"
display = "standalone"
